Add methods to allow get/set of websocket client ping interval
espressif/esp-protocols pull request #22
Opened 2022-03-17 12:57 UTC by 0xFEEDC0DE64

[Redo of espressif/esp-idf pull 8486](https://github.com/espressif/esp-idf/pull/8486)

2022-04-01 19:10 UTC, gabsuren commented
@0xFEEDC0DE64 thanks for your contribution. The changes LGTM. Some minor nitpicks left.

2022-04-06 13:17 UTC, gabsuren requested changes

2022-04-06 13:25 UTC, gabsuren commented on components/esp_websocket_client/esp_websocket_client.c
> +        ESP_LOGW(TAG, "invalid client");
```suggestion
        ESP_LOGW(TAG, "Client was not initialized");
```

2022-04-06 13:30 UTC, gabsuren requested changes

2022-04-06 13:30 UTC, gabsuren commented on components/esp_websocket_client/esp_websocket_client.c
> +        ESP_LOGW(TAG, "no config available to change the ping interval for");
```suggestion
        ESP_LOGW(TAG, "No config available to change the ping interval");
```

2022-04-06 13:30 UTC, gabsuren commented on components/esp_websocket_client/esp_websocket_client.c
> +        ESP_LOGW(TAG, "no config available to change the ping interval for");
```suggestion
        ESP_LOGW(TAG, "No config available to change the ping interval");
```

2022-04-06 13:30 UTC, gabsuren commented on components/esp_websocket_client/esp_websocket_client.c
> +        return ESP_ERR_INVALID_ARG;
```suggestion
        ESP_LOGW(TAG, "Client was not initialized");
        return ESP_ERR_INVALID_ARG;
```

2022-04-06 13:32 UTC, gabsuren commented
@0xFEEDC0DE64 thanks for your contribution. The changes LGTM. Some minor nitpicks left.

2022-04-26 09:02 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/espressif/esp-protocols?pullRequest=22) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/espressif/esp-protocols?pullRequest=22) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/espressif/esp-protocols?pullRequest=22) it.</sub>

2022-04-26 09:06 UTC, 0xFEEDC0DE64 commented
Did a rebase + squash

2022-04-28 12:03 UTC, gabsuren approved these changes
LGTM!

2022-05-03 07:26 UTC, david-cermak approved these changes

2022-05-03 07:26 UTC, merged