Unite all tags under common structure
espressif/esp-protocols pull request #223
Opened 2023-02-15 13:33 UTC by AndriiFilippov

Made the logging tags lower case.

2023-02-15 13:33 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/espressif/esp-protocols?pullRequest=223) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/espressif/esp-protocols?pullRequest=223) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/espressif/esp-protocols?pullRequest=223) it.</sub>

2023-02-15 14:06 UTC, david-cermak commented on components/mdns/examples/main/mdns_example_main.c
> +    ESP_ERROR_CHECK(mdns_netif_action(EXAMPLE_INTERFACE, MDNS_EVENT_ENABLE_IP4 | MDNS_EVENT_ENABLE_IP6));
Unrelated change. Probably an issue with rebasing?

2023-02-15 14:06 UTC, david-cermak requested changes
Please rebase

2023-02-15 14:54 UTC, AndriiFilippov commented
> Please rebase

done

2023-02-15 18:32 UTC, david-cermak approved these changes

2023-02-15 18:44 UTC, david-cermak commented on components/esp_websocket_client/examples/main/websocket_example.c
> +static const char *TAG = "websocket";
This need a fix in the test code, see the failure here: https://github.com/espressif/esp-protocols/actions/runs/4185017500/jobs/7256313908#step:6:292

Please update the `pytest`, as well

2023-02-15 18:46 UTC, david-cermak requested changes
Please fix the CI

2023-02-17 14:08 UTC, david-cermak approved these changes

2023-02-17 14:08 UTC, merged