Implement websocket client connect error
espressif/esp-protocols pull request #23
Opened 2022-03-17 13:07 UTC by 0xFEEDC0DE64

[Redo of espressif/esp-idf pull 8455](https://github.com/espressif/esp-idf/pull/8455)

I dont know why, but the current websocket client implementation keeps emitting a DISCONNECTED event when the host address is simply wrong.

To me it seems more clear that this is an error case and usually you have not been connected before, so emitting a DISCONNECTED doesnt seem right?

Let me know what you think

2022-04-07 16:33 UTC, gabsuren requested changes
@0xFEEDC0DE64 the changes LGTM in general, just one note remained. 
Thanks

2022-04-07 16:33 UTC, gabsuren commented on components/esp_websocket_client/esp_websocket_client.c
> +        client->wait_timeout_ms = WEBSOCKET_RECONNECT_TIMEOUT_MS;
@0xFEEDC0DE64 Please remove this line, as `client->wait_timeout_ms` is already initialized either to default `WEBSOCKET_RECONNECT_TIMEOUT_MS` or to `config->reconnect_timeout_ms` during client initialization

2022-04-26 09:17 UTC, 0xFEEDC0DE64 commented
Did a rebase + implemented review comment + sqaush

2022-04-27 10:24 UTC, gabsuren approved these changes
LGTM!

2022-04-27 13:52 UTC, merged