feat(websocket): Added linux port for websocket
espressif/esp-protocols pull request #310
Opened 2023-06-20 10:32 UTC by gabsuren

2023-06-20 10:32 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/espressif/esp-protocols?pullRequest=310) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/espressif/esp-protocols?pullRequest=310) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/espressif/esp-protocols?pullRequest=310) it.</sub>

2023-06-27 15:40 UTC, david-cermak requested changes

2023-06-27 15:40 UTC, david-cermak commented on .github/workflows/publish-coverage-report.yml
> +          path: $GITHUB_WORKSPACE/artifact1
could we give it a better name? instead of `artifact1` something like `modem_coverage_report`, or similar?

2023-06-27 15:40 UTC, david-cermak commented on .github/workflows/websocket__build-host-tests.yml
> +          thresholds: '60 80'
This could be probably made a reusable workflow

2023-06-27 15:40 UTC, david-cermak commented on .github/workflows/websocket__build-target-test.yml
> +        test: [ { app: example, path: "examples" }, { app: unit_test, path: "test/unit_test" } ]
suggest that we call the test folder `tests` (plural), same as `examples`

2023-06-27 15:40 UTC, david-cermak commented on components/esp_websocket_client/CMakeLists.txt
> +target_compile_options(${COMPONENT_LIB} PRIVATE "-Wno-format")
Please remove

2023-06-27 15:40 UTC, david-cermak commented on components/esp_websocket_client/esp_websocket_client.c
> +#define BIT1   0x00000002
can we use bit definitions from `esp_system` ?

2023-06-27 15:40 UTC, david-cermak commented on components/esp_websocket_client/test/host_test/main/CMakeLists.txt
> +target_compile_definitions(${COMPONENT_LIB} PRIVATE "-DCONFIG_IDF_TARGET_LINUX")
This shouldn't be needed. The build system should add this (might need to include `sdkconfig.h`)

2023-06-27 15:40 UTC, david-cermak commented on .github/workflows/websocket__build-host-tests.yml
> +          ./build/websocket-host.elf -r junit -o junit.xml
This is not a test, why the `junit` parameters?
```suggestion
          ./build/websocket-host.elf
```

2023-07-24 06:47 UTC, david-cermak commented on components/esp_websocket_client/examples/linux/main/main.c
Question: Is this a copy-paste of `components/esp_websocket_client/examples/target/main/main.c` or how much they differ? Could we just reuse the same example and make it work for both linux and ESP target?

2023-07-24 06:47 UTC, david-cermak reviewed
LGTM, just one question about reusing the example

2023-07-26 09:43 UTC, gabsuren commented
@david-cermak  thank you for the review.
As for the existing target example, it required the use of components esp_netif, esp_timer, esp_wifi, and json. For the esp_netif, we needed to utilize the existing solution from esp_modem. I decided to address this within the scope of another story [Update/support of linux port for all existing components to support common reusable actions, headers, workflows](https://jira.espressif.com:8443/browse/IDF-7856)

2023-07-27 05:49 UTC, david-cermak approved these changes

2023-07-27 07:07 UTC, merged