mdns: Initial version based on IDF 5.0
espressif/esp-protocols pull request #43
Opened 2022-05-27 14:10 UTC by gabsuren

2022-05-27 14:10 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/espressif/esp-protocols?pullRequest=43) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/espressif/esp-protocols?pullRequest=43) before we can accept your contribution.<br/>**2** out of **13** committers have signed the CLA.<br/><br/>:white_check_mark: david-cermak<br/>:white_check_mark: suren-gabrielyan-espressif<br/>:x: Caffreyfans<br/>:x: Dazza0<br/>:x: dobairoland<br/>:x: o-marshmallow<br/>:x: h2zero<br/>:x: 0xjakob<br/>:x: ESP-Marius<br/>:x: antmak<br/>:x: kostaond<br/>:x: sudeep-mohanty<br/>:x: laukik-hase<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/espressif/esp-protocols?pullRequest=43) it.</sub>

2022-05-31 07:15 UTC, david-cermak requested changes
LGTM in general. There are some minor point that I'm not convinced about:
1) GitHub action files (file names and names of actions and sub-actions) and their structure
2) Structure of tests -- `test_apps`, `test`, `host_test` in component root
3) Tests are not implemented/executed in the CI
4) `common_components` folder for the connection utility

But this could be addressed in future PRs...

2022-05-31 07:15 UTC, david-cermak commented on docs/docs_versions.js
> +        { name: "v4.4.1", old:false, has_targets:true, supported_targets: [ "esp32", "esp32s2", "esp32s3", "esp32c3" ]},
I thought this version file describes the actual component, not IDF.

2022-05-31 07:15 UTC, david-cermak commented on .github/workflows/test_afl_fuzzer.yml
> +name: Test AFL fuzzer host (mDNS)
This only checks that the mdns fuzzer layers compile, correct? We shouldn't call it `AFL fuzzer`...

2022-05-31 11:18 UTC, gabsuren commented on common_components/protocol_examples_common/Kconfig.projbuild
> +menu "Example Connection Configuration"
https://github.com/espressif/esp-protocols/pull/26#discussion_r842677518

2022-06-01 09:14 UTC, david-cermak commented on components/mdns/docs/en/index.rst
> + - mDNS creates a task with default low priority 1 `CONFIG_MDNS_TASK_PRIORITY` (If `CONFIG_FREERTOS_UNICORE` enabeled it pinned to CPU0 (`CONFIG_MDNS_TASK_AFFINITY`).
```suggestion
 - mDNS creates a task with default low priority 1 `CONFIG_MDNS_TASK_PRIORITY` (If ``CONFIG_FREERTOS_UNICORE`` enabeled it pinned to CPU0 (`CONFIG_MDNS_TASK_AFFINITY`).
```

2022-06-02 10:33 UTC, gabsuren commented
@david-cermak thanks for the review, updated accordingly and created new task to implement tests in CI
[IDFGH-7525](https://jira.espressif.com:8443/browse/IDFGH-7525)

2022-06-03 10:57 UTC, david-cermak approved these changes
Thanks for the latest updates. LGTM!

2022-06-03 10:57 UTC, merged